movie_library/models.py
from dataclasses import dataclass, field
from datetime import datetime


@dataclass
class Movie:
    _id: str
    title: str
    director: str
    year: int
    cast: list[str] = field(default_factory=list)
    series: list[str] = field(default_factory=list)
    last_watched: datetime = None
    rating: int = 0
    tags: list[str] = field(default_factory=list)
    description: str = None
    video_link: str = None

@dataclass
class User:
    _id: str
    email: str
    password: str
    movies: list[str] = field(default_factory=list)

movie_library/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, SubmitField, TextAreaField, URLField, PasswordField

from wtforms.validators import InputRequired, NumberRange, Email, EqualTo, Length


class MovieForm(FlaskForm):
    title = StringField("Title", validators=[InputRequired()])
    director = StringField("Director", validators=[InputRequired()])

    year = IntegerField(
        "Year",
        validators=[
            InputRequired(),
            NumberRange(min=1878, message="Please enter a year in the format YYYY."),
        ],
    )

    submit = SubmitField("Add Movie")


class StringListField(TextAreaField):
    def _value(self):
        if self.data:
            return "\n".join(self.data)
        else:
            return ""

    def process_formdata(self, valuelist):
        # checks valuelist contains at least 1 element, and the first element isn't falsy (i.e. empty string)
        if valuelist and valuelist[0]:
            self.data = [line.strip() for line in valuelist[0].split("\n")]
        else:
            self.data = []

class ExtendedMovieForm(MovieForm):
    cast = StringListField("Cast")
    series = StringListField("Series")
    tags = StringListField("Tags")
    description = TextAreaField("Description")
    video_link = URLField("Video link")

    submit = SubmitField("Submit")

class RegisterForm(FlaskForm):
    email = StringField("Email", validators=[InputRequired(), Email()])

    password = PasswordField(
        "Password",
        validators=[
            InputRequired(),
            Length(
                min=4,
                max=20,
                message="Your password must be between 4 and 20 characters long.",
            ),
        ],
    )

    confirm_password = PasswordField(
        "Confirm Password",
        validators=[
            InputRequired(),
            EqualTo(
                "password",
                message="This password did not match the one in the password field.",
            ),
        ],
    )

    submit = SubmitField("Register")

class LoginForm(FlaskForm):
    email = StringField("Email", validators=[InputRequired(), Email()])
    password = PasswordField("Password", validators=[InputRequired()])
    submit = SubmitField("Login")

movie_library/__init__.py
import os
from flask import Flask
from dotenv import load_dotenv
from pymongo import MongoClient

from movie_library.routes import pages

load_dotenv()

def create_app():
    app = Flask(__name__)
    app.config["MONGODB_URI"] = os.environ.get("MONGODB_URI")
    app.config["SECRET_KEY"] = os.environ.get(
        "SECRET_KEY", "pf9Wkove4IKEAXvy-cQkeDPhv9Cb3Ag-wyJILbq_dFw"
    )
    app.db = MongoClient(app.config["MONGODB_URI"]).get_default_database('test')

    app.register_blueprint(pages)

    return app

movie_library/routes.py
from flask import Blueprint, render_template, redirect, session, request, current_app, url_for, flash
from movie_library.forms import MovieForm, ExtendedMovieForm, RegisterForm, LoginForm
from movie_library.models import Movie, User
from dataclasses import asdict
import uuid
import datetime
from passlib.hash import pbkdf2_sha256
import functools

pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)

def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))

        return route(*args, **kwargs)

    return route_wrapper


@pages.route("/")
@login_required
def index():
    user_data = current_app.db.user.find_one({"email": session["email"]})
    user = User(**user_data)
    movie_data = current_app.db.movie.find({"_id": {"$in": user.movies}})
    movies = [Movie(**movie) for movie in movie_data]
    return render_template(
        "index.html",
        title="Movies Watchlist", movies_data=movies
    )

@pages.get("/toggle-theme")
def toggle_theme():
    current_theme = session.get("theme")
    if current_theme == "dark":
        session["theme"] = "light"
    else:
        session["theme"] = "dark"

    return redirect(request.args.get("current_page"))

@pages.route("/add", methods=["GET", "POST"])
@login_required
def add_movie():
    form = MovieForm()

    if form.validate_on_submit():
        movie = Movie(
            _id=uuid.uuid4().hex,
            title=form.title.data,
            director=form.director.data,
            year=form.year.data,
        )

        current_app.db.movie.insert_one(asdict(movie))
        current_app.db.user.update_one({"_id": session["user_id"]}, {"$push": {"movies": movie._id}})

        #return redirect(url_for(".index"))
        return redirect(url_for(".movie", _id=movie._id))
        
    return render_template(
        "new_movie.html", title="Movies Watchlist - Add Movie", form=form
    )

@pages.get("/movie/<string:_id>")
def movie(_id: str):
    movie = Movie(**current_app.db.movie.find_one({"_id": _id}))
    return render_template("movie_details.html", movie=movie)


@pages.get("/movie/<string:_id>/rate")
@login_required
def rate_movie(_id):
    rating = int(request.args.get("rating"))
    current_app.db.movie.update_one({"_id": _id}, {"$set": {"rating": rating}})

    return redirect(url_for(".movie", _id=_id))


@pages.get("/movie/<string:_id>/watch")
@login_required
def watch_today(_id):
    current_app.db.movie.update_one(
        {"_id": _id}, {"$set": {"last_watched": datetime.datetime.today()}}
    )

    return redirect(url_for(".movie", _id=_id))

@pages.route("/edit/<string:_id>", methods=["GET", "POST"])
@login_required
def edit_movie(_id: str):
    movie = Movie(**current_app.db.movie.find_one({"_id": _id}))
    form = ExtendedMovieForm(obj=movie)
    if form.validate_on_submit():
        movie.title = form.title.data
        movie.director = form.director.data
        movie.year = form.year.data
        movie.cast = form.cast.data
        movie.series = form.series.data
        movie.tags = form.tags.data
        movie.description = form.description.data
        movie.video_link = form.video_link.data

        current_app.db.movie.update_one({"_id": movie._id}, {"$set": asdict(movie)})
        return redirect(url_for(".movie", _id=movie._id))
    return render_template("movie_form.html", movie=movie, form=form)

@pages.route("/register", methods=["POST", "GET"])
def register():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = RegisterForm()

    if form.validate_on_submit():
        user = User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(form.password.data),
        )

        current_app.db.user.insert_one(asdict(user))

        flash("User registered successfully", "success")

        return redirect(url_for(".login"))

    return render_template(
        "register.html", title="Movies Watchlist - Register", form=form
    )

@pages.route("/login", methods=["GET", "POST"])
def login():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = LoginForm()

    if form.validate_on_submit():
        user_data = current_app.db.user.find_one({"email": form.email.data})
        if not user_data:
            flash("Login credentials not correct", category="danger")
            return redirect(url_for(".login"))
        user = User(**user_data)

        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            session["user_id"] = user._id
            session["email"] = user.email

            return redirect(url_for(".index"))

        flash("Login credentials not correct", category="danger")

    return render_template("login.html", title="Movies Watchlist - Login", form=form)

@pages.route("/logout")
def logout():
    current_theme = session.get("theme")
    session.clear()
    session["theme"] = current_theme

    return redirect(url_for(".login"))

movie_library/templates/index.html
{% extends "layout.html" %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/movies.css') }}" />
{% endblock %} {% block main_content %} {% if movies_data %}
<table class="table">
  <colgroup>
    <col style="width: 60%" />
    <col style="width: 25%" />
    <col style="width: 15%" />
  </colgroup>
  <thead>
    <tr class="table__header">
      <th class="table__cell table__cell--header">Title</th>
      <th class="table__cell table__cell--header">Release Date</th>
      <th class="table__cell table__cell--header"></th>
    </tr>
  </thead>
  <tbody>
    {% for movie in movies_data %}
    <tr>
      <td class="table__cell">
        <p class="table__movieTitle">{{ movie.title }}</p>
        <p class="table__movieDirector">By {{ movie.director }}</p>
      </td>
      <td class="table__cell">{{ movie.year }}</td>
      <td class="table__cell"><a href="{{ url_for(".movie", _id=movie._id) }}" class="table__link">View</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p class="table__empty">
  You haven't added any movies yet.
  <a href="{{ url_for('pages.add_movie') }}" class="link">Add one!</a>
</p>
{% endif %}

<a href="{{ url_for('pages.add_movie') }}" class="button button--add">
  <span>+</span>
</a>

{% endblock %}

movie_library/templates/layout.html
{% from "macros/nav.html" import header %} {% from "macros/footer.html" import
footer %}

<html lang="en" class="{{ 'dark-mode' if session.get('theme') == 'dark' }}">
     <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
         <meta http-equiv="X-UA-Compatible" content="ie=edge" />
         <title>{{ title | default('Movie Watchlist') }}</title>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{{ title | default('Movie Watchlist') }}</title>
    <link
      href="https://fonts.googleapis.com/css?family=Public+Sans:400,600&display=swap"
      rel="stylesheet" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/reset.css') }}" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css') }}" />

    {% block head_content %} {% endblock %}
  </head>

  <body>
    {{ header(session.get("email"),session.get("theme")) }}
    <main class="main">{% block main_content %} {% endblock %}</main>
    {{ footer() }}
  </body>
</html>

movie_library/templates/login.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %} 

{% block main_content %}

    <form name="login" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}

        <div class="form__container">
            {{ form.hidden_tag() }}
    
            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
    
            <span class="form__small">
                Don't have an account? <a href="{{ url_for('pages.register') }}" class="form__link">Register here</a>.
            </span>
    
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

movie_library/templates/macros/fields.html
{% macro render_text_field(field) %}
<div class="form__group">
    {{ field.label(class_="form__label") }}
    {{ field(class_="form__field") }}

    {%- for error in field.errors %}
        <span class="form__error">{{ error }}</span>
    {% endfor %}
</div>
{% endmacro %}

{% macro render_area_field(field) %}
<div class="form__group">
    {{ field.label(class_="form__label") }}
    {{ field(rows=4, class_="form__field", style="resize: none") }}

    {%- for error in field.errors %}
        <span class="form__error">{{ error }}</span>
    {% endfor %}
</div>
{% endmacro %} 

movie_library/templates/macros/footer.html
{% macro footer() %}
<footer class="footer">
    <small>Copyright &copy;2022. Movies Watchlist. All rights reserved.</small>
</footer>
{% endmacro %}

movie_library/templates/macros/nav.html
{% from "macros/svgs.html" import moon,sun %} {% macro header(email,theme) %}
<header class="header">
  <div class="nav-container">
    <a href="{{ url_for('pages.index') }}" class="header__logo">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="logo__icon"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z" />
      </svg>
      <span class="logo__name">Watchlist</span>
    </a>
    <nav class="nav">
      {% if not email %}
      <a
        href="{{ url_for('pages.login') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.login') }}">
        <span class="nav__item">Log in</span>
      </a>
      <a
        href="{{ url_for('pages.register') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.register') }}">
        <span class="nav__item">Register</span>
      </a>
      <a
        href="{{ url_for('pages.toggle_theme', current_page=request.path) }}"
        class="nav__link">
        <span class="nav__item">
          {% if theme == "dark" %} {{ sun("nav__icon") }} {% else %} {{
          moon("nav__icon") }} {% endif %}
        </span>
      </a>

      {% else %}
      <a
        href="{{ url_for('pages.index') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.index') }}">
        <span class="nav__item">Movies</span>
      </a>
      <a href="{{ url_for('pages.logout') }}" class="nav__link">
        <span class="nav__item">Log out</span>
      </a>
      {% endif %}
    </nav>
  </div>
</header>
{% endmacro %}

movie_library/templates/macros/svgs.html
{% macro star(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
</svg>
{% endmacro %}

{% macro pencil(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
</svg>
{% endmacro %}

{% macro moon(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
</svg>
{% endmacro %}

{% macro sun(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
</svg>
{% endmacro %}

movie_library/templates/movie_details.html
{% from "macros/svgs.html" import star, pencil %} {% extends "layout.html" %}
{%- block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/movie_details.css') }}" />
{% endblock %} {% block main_content %}
<div class="container">
  <header class="movie__header">
    <div class="header__row">
      <div class="movie__name">
        <h1>{{ movie.title }}</h1>
        <div class="movie__rating">
            {% for i in range(5) %}
    <a class="rating__link" href="{{ url_for('pages.rate_movie', _id=movie._id, rating=i+1) }}">
        {{ star("star " + ("star--filled" if movie.rating > i else "")) }}
    </a>
{% endfor %}
</div>
      </div>
      <div class="movie__watched">
        {% if movie.last_watched %}
        <p>
            Last watched: <a href="{{ url_for('pages.watch_today', _id=movie._id) }}" class="watched__link">
            <time datetime="{{ movie.last_watched }}"
              >{{movie.last_watched.strftime("%d %b %Y")}}</time
            >
          </a>
        </p>
        {% else %}
        <p><a href="{{ url_for('pages.watch_today', _id=movie._id) }}" class="watched__link">Not watched yet</a></p>        {% endif %}
        <a class="movie__edit" href="{{ url_for('pages.edit_movie', _id=movie._id) }}">Edit {{ pencil("pencil") }}</a>      </div>
    </div>
    <div class="header__row">
      <ul class="movie__tags">
        {% for tag in movie.tags %}
        <li class="movie__tag">{{ tag }}</li>
        {% endfor %}
      </ul>
    </div>
  </header>
</div>
{% if movie.video_link %}
<iframe
    class="movie__video"
    src="{{ movie.video_link }}"
    title="YouTube video player"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen>
</iframe>
{% endif %}

{% if movie.description %}
    <p class="movie__description">{{ movie.description }}</p>
{% else %}
    <p class="movie__description">No description yet. <a class="link" href="{{ url_for('pages.edit_movie', _id=movie._id) }}">Add one?</a></p>
{% endif %}

<div class="movie__meta">
    {% if movie.cast %}
        <div class="movie__casting">
            <h2>Casting</h2>
            <ul class="list">
            {% for actor in movie.cast %}
                <li class="list__item">{{ actor }}</li>
            {% endfor %}
            <ul>
        </div>
    {% endif %}
    {% if movie.series | length %}
        <div class="movie__series">
            <h2>Series</h2>
            <ul class="list">
            {% for movie_in_series in movie.series %}
                <li class="list__item">{{ movie_in_series }}</li>
            {% endfor %}
            <ul>
        </div>
    {% endif %}
</div>
{% endblock %}

movie_library/templates/movie_form.html
{% from "macros/fields.html" import render_text_field, render_area_field %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

    <form name="add_movie" method="post" novalidate class="form">
        <div class="form__container">
            {{ form.hidden_tag() }}
            {{ render_text_field(form.title) }}
            {{ render_text_field(form.director) }}
            {{ render_text_field(form.year) }}

            {{ render_area_field(form.cast) }}
            {{ render_area_field(form.series) }}
            {{ render_area_field(form.tags) }}

            {{ render_area_field(form.description) }}
            {{ render_text_field(form.video_link) }}
    
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

movie_library/templates/new_movie.html
{% from "macros/fields.html" import render_text_field %} {% extends
"layout.html" %} 

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}
<form name="add_movie" method="post" novalidate class="form">
  <div class="form__container">
    {{ form.hidden_tag() }} {{ render_text_field(form.title) }} {{
    render_text_field(form.director) }} {{ render_text_field(form.year) }}

    <div>{{ form.submit(class_="button button--form") }}</div>
  </div>
</form>
{% endblock %}

movie_library/templates/register.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %} 

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %} 

{% block main_content %}

    <form name="register" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}
        
        <div class="form__container">
            {{ form.hidden_tag() }}

            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
            {{ render_text_field(form.confirm_password) }}
    
            <span class="form__small">
                Already have an account? <a href="{{ url_for('pages.login') }}" class="form__link">Log in here</a>.
            </span>
    
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}